import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-about-page',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './about-page.component.html',
  styleUrl: './about-page.component.css',
})
export class AboutPageComponent {
  visability: boolean[] = new Array(3).fill(false);
  questions: string[] = [
    'How does Ai Learner create quizzes from study material?',
    ' Is the content generated by OpenAI’s API reliable?',
    ' Can I track my learning progress on your platform?',
    "What makes 'Ai Learner' different from other study tools?",
  ];
  answers: string[] = [
    "Our platform uses OpenAI’s API to analyze your study materials and generate quizzes with questions that reflect the core concepts of your content. It's automated, accurate, and tailored to your needs.",
    " Yes, we trust in the reliability of OpenAI's API, which is designed to provide accurate and contextually relevant content. However, we always recommend reviewing the material for a personalized touch.",
    "Absolutely! Our platform provides detailed analytics on your quiz performances, helping you identify strengths and areas for improvement. With OpenAI's API, we provide insights that help you learn smarter.",
    "Our use of OpenAI's API allows for a highly personalized anddynamic learning experience that adapts to your individual learning pace and style. It’s more than a study tool; it's a personal learning assistant.",
  ];

  changeVisability(index: number) {
    this.visability[index] = !this.visability[index];
  }
}
